### ISSUE TITLE
Sony .ARW files geotagged by gpscorrelate rejected by Lightroom

### ISSUE THREAD

**Issue by fugwort** [dfandrich/gpscorrelate#18]
gpscorrelate V2.0; Lightroom V6.14; .ARW files from RX100M3

I geotagged some .ARW files with gpscorrelate and tried to import them into Lightroom.  Lightroom gave the error message "Failed to find a place for the imported file. (3).  Included in the same import was an .ARW file not gotagged, which Lightroom accepted.  I verified that the .ARW files were correctly geotagged by opening them with nomacs, which can display the photo's locations on a map.

I was able to geotag some .CR2 files from a Canon G12.  Lightroom accepted those files.

**Comment by dfandrich** [comment]
What happens if you manipulate the same files using the exiv2 command-line? Try adding a random tag and see how Lightroom reacts. It may have something to do with libexiv2. Can you supply a file that Lightroom doesn't like?

**Comment by fugwort** [comment]
Sorry for the delay in responding.  My camera is being repaired, so I
can't get a picture and corresponding GPS track.  It will be several
weeks before the camera is fixed.  I'll get back to you then.

John Yates

**Comment by dfandrich** [comment]
In the absence of a test file to verify the problem, I'm going to assume the issue is related to libexiv2, not gpscorrelate. gpscorrelate leaves all the file handling up to exiv2, so as long as the tags written are correct (and I haven't heard of other programs complainin), an issue with another program opening the file is most likely to do with ARW support in exiv2.
